#!/usr/bin/env php
<?php

include_once './vendor/autoload.php';

$app = new Symfony\Component\Console\Application('OpenAPI Client Generator', '0.2');
$app->add(new Rygilles\OpenApiPhpClientGenerator\GenerateCommand);
$app->run();
