#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}
$app = new Symfony\Component\Console\Application('OpenAPI Client Generator', '0.1');
$app->add(new Rygilles\OpenApiPhpClientGenerator\GenerateCommand);
$app->run();


